
# PureChat by 64FF00 (xktiverz@gmail.com, @64ff00 for Twitter)

---

# PureChat version string
# - string
version: "1.4.0-BETA-04"

# Set default clans plugin for PureChat
# - ClansPro / FahmiCyber-Clans (§l§9-§8]§b>§7[§cFahmi§aTestSrv§7]§b<§8[§9-) / null
default-clans-plugin: ...

# Enable this if you want to use per-world chat formats / per-world nametags for players
# - true / false
enable-multiworld-chat: false

# Please check if you have all PurePerms groups in your server here

# &0: Black, &1: Dark Blue, &2: Dark Green, &3: Dark Aqua, &4: Dark Red, &5: Dark Purple, &6: Gold, &7: Gray, &8: Dark Gray, &9: Blue
# &a: Green, &b: Aqua, &c: Red, &d: Light Purple, &e: Yellow, &f: White
# &k: Obfuscated, &l: Bold, &m: Strikethrough, &n: Underline, &o: Italic, &r: Reset

# Available PureChat tags: {display_name}, {msg}, {clan_name}, {clan_rank}, {prefix}, {suffix}, {world}
groups:
  Owner:
    nametag: '&8&l[§f?§4Own§cer§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|§f{msg}§9|«§•]&f&r
      {display_name}'
    chat: '&8&l[§f?§4Own§cer§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|§f{msg}§9|«§•]&f&r
      {display_name} &7> {msg}'
  CoOwner:
    nametag: '&8&l[§f?§1CoO§9wner§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|{msg}|«§•]&f&r
      {display_name}'
    chat: '&8&l[§f?§1CoO§9wner§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|§f{msg}§9|«§•]&f&r
      {display_name} &7> {msg}'
  Admin:
    nametag: '&8&l[§f?§2Ad§amin§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|{msg}|«§•]&f&r
      {display_name}'
    chat: '&8&l[§f?§2Ad§amin§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|§f{msg}§9|«§•]&f&r
      {display_name} &7> {msg}'
  Builder:
    nametag: '&8&l[§f?§3Buil§bder§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|{msg}|«§•]&f&r
      {display_name}'
    chat: '&8&l[§f?§3Buil§bder§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|§f{msg}§9|«§•]&f&r
      {display_name} &7> {msg}'
  Newbie:
    nametag: '&8&l[§f?§8New§7bie§f?§8]§6=•=§8[§9{cla_name}§8]§6|§7{display_name}§6|§9»|{msg}|«§•]&f&r
      {display_name}'
    chat: '&8&l[§f?§8New§7bie§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|§f{msg}§9|«§•]&f&r
      {display_name} &7> {msg}'
  BeginnerRank:
    nametag: '&8&l[§f?§5Begin§dner§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|{msg}|«§•]&f&r
      {display_name}'
    chat: '&8&l[§f?§5Begin§dner§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|§f{msg}§9|«§•]&f&r
      {display_name} &7> {msg}'
  RookieRank:
    nametag: '&8&l[§f?§6Roo§ekie§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|{msg}|«§•]&f&r
      {display_name}'
    chat: '&8&l[§f?§6Roo§ekie§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|§f{msg}§9|«§•]&f&r
      {display_name} &7> {msg}'
  AmateurRank:
    nametag: '&8&l[§f?§2Ama§ateur§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|§f{msg}§9|«§•]&f&r
      {display_name}'
    chat: '&8&l[§f?§2Ama§ateur§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|{msg}|«§•]&f&r
      {display_name} &7> {msg}'
  ProRank:
    nametag: '&8&l[§f?§1P§9ro§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|§f{msg}§9|«§•]&f&r
      {display_name}'
    chat: '&8&l[§f?§1P§9ro§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|{msg}|«§•]&f&r
      {display_name} &7> {msg}'
  IntermediateRank:
    nametag: '&8&l[§f?§4Inter§cmediate§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|§f{msg}§9|«§•]&f&r
      {display_name}'
    chat: '&8&l[§f?§4Inter§cmediate§f?§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|{msg}|«§•]&f&r
      {display_name} &7> {msg}'
  Helper:
    nametag: '&8&l[§f©§6Hel§eper§f©§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|§f{msg}§9|«§•]&f&r
      {display_name}'
    chat: '&8&l[§f©§6Hel§eper§f©§8]§6=•=§8[§9{clan_name}§8]§6|§7{display_name}§6|§9»|§f{msg}§9|«§•]&f&r
      {display_name} &7> {msg}'
...